name: Run Nox Sessions
on:
  push:
    branches: [main]
  pull_request:
jobs:
  run-nox:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install nox
        run: python -m pip install --upgrade pip nox
      - name: Run nox default session
        run: nox
